<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login.gov_OneTimeCode-TxtBx</name>
   <tag></tag>
   <elementGuidId>5c8534bd-93e1-4e39-904e-1fea93979c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;code-53895&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;code-53895&quot;]</value>
      <webElementGuid>9a9ba673-682f-4c2a-98d6-1d097893f9a3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
