<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginDialogLinkToLogin-Link</name>
   <tag></tag>
   <elementGuidId>a73d364d-e7f8-4025-a8ed-8e13dad1eb68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;loginDialogLinkToLogin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;loginDialogLinkToLogin&quot;]</value>
      <webElementGuid>5ba1c355-0432-437f-a5ab-d964d006b97e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
