<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login.gov-Btn</name>
   <tag></tag>
   <elementGuidId>0281b768-0b8a-4b44-8ce1-c53e1e3ab77a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='external-login-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='external-login-button']</value>
      <webElementGuid>a1af9bb3-77b6-446d-9d4f-52b5256b481d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
