<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login.gov_UserEmail-TxtBx</name>
   <tag></tag>
   <elementGuidId>d2a4c4cc-4bc8-4298-ae65-239bf49ecc2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;user_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;user_email&quot;]</value>
      <webElementGuid>6b98da02-babf-4046-bdc4-4c3890067ea6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
