<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddContact-Btn</name>
   <tag></tag>
   <elementGuidId>a1f4b4bd-f8d9-43a5-834c-fca4cd8be36a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-a-add-additional-contact-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-a-add-additional-contact-button&quot;]</value>
      <webElementGuid>3ba68846-1afe-461c-b7d6-6ec9e73072c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
