<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdditionalContact_Position-Txtbx</name>
   <tag></tag>
   <elementGuidId>2bc80516-6d2e-43a1-a7c9-0f13d1d7942a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-aadditionalContacts-0-position&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-aadditionalContacts-0-position&quot;]</value>
      <webElementGuid>903477de-9424-4dea-a37e-f67f20a51533</webElementGuid>
   </webElementProperties>
</WebElementEntity>
