<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdditionalContact_Email-Txtbx</name>
   <tag></tag>
   <elementGuidId>92b12292-90c8-45f4-9cd0-b0a418ad599e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-aadditionalContacts-0-email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-aadditionalContacts-0-email&quot;]</value>
      <webElementGuid>d5afa694-6311-4a32-ab05-e98adfaaddd3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
