<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdditionalContact_LastName-Txtbx</name>
   <tag></tag>
   <elementGuidId>a3b32b10-3ed3-41d7-a44d-3c5c8c887a3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-aadditionalContacts-0-last-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-aadditionalContacts-0-last-name&quot;]</value>
      <webElementGuid>0eb89df1-d6b4-43aa-8dfd-f93c12e42709</webElementGuid>
   </webElementProperties>
</WebElementEntity>
