<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PI_EraCommonsAccount-Txtbx</name>
   <tag></tag>
   <elementGuidId>c3515d1e-e314-4afd-9d1c-66ff2cc7744b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-a-pi-era-commons-account&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-a-pi-era-commons-account&quot;]</value>
      <webElementGuid>c6cc94be-32bb-483b-a69c-d313b6a7282d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
