<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PI_Institution-Dd</name>
   <tag></tag>
   <elementGuidId>6b2bbabe-477e-4fe9-89ea-62d26b4bbb4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-a-pi-institution&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-a-pi-institution&quot;]</value>
      <webElementGuid>07755ba5-e9ad-4d30-9a32-15af5fbd3627</webElementGuid>
   </webElementProperties>
</WebElementEntity>
