<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PrimContact_Institution-Dd</name>
   <tag></tag>
   <elementGuidId>ba7aecb9-73a1-42b9-9544-ca621c77fdac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-a-primary-contact-institution&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-a-primary-contact-institution&quot;]</value>
      <webElementGuid>b085329f-d2ed-4980-80c0-8499faafb764</webElementGuid>
   </webElementProperties>
</WebElementEntity>
