<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PrimContact_LastName-Txtbx</name>
   <tag></tag>
   <elementGuidId>4ab819f1-cc58-4423-b34e-0d89e35313be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-a-primary-contact-last-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-a-primary-contact-last-name&quot;]</value>
      <webElementGuid>f4a8725b-6eee-44ba-b1e4-ebd26053330e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
