<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PrimContact_Email-Txtbx</name>
   <tag></tag>
   <elementGuidId>5f2f9770-8f38-40f9-a6aa-a6e97be50f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-a-primary-contact-email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-a-primary-contact-email&quot;]</value>
      <webElementGuid>854efbe5-8922-4874-9f37-cdb9ea2f10ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
