<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RemoveContact-Btn</name>
   <tag></tag>
   <elementGuidId>49bbed45-d9c6-4951-a56c-1d8a4ba3e37a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-aadditionalContacts-0-remove-contact-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-aadditionalContacts-0-remove-contact-button&quot;]</value>
      <webElementGuid>4072431c-c284-4af1-a4e6-8476b750775b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
