<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trials_CloseView_Btn</name>
   <tag></tag>
   <elementGuidId>2b69dbde-d02d-4387-9bb1-f7a011ada5e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div/div[2]/div/div[2]/div[1]/div[1]/div[2]/label/button/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div/div[2]/div/div[2]/div[1]/div[1]/div[2]/label/button/span[1]</value>
   </webElementProperties>
</WebElementEntity>
