<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OtherCancerTypeNotIncluded-Txtbx</name>
   <tag></tag>
   <elementGuidId>9f45e6d8-37e3-46b1-b83a-b8bd4b0242a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-other-cancer-types&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-other-cancer-types&quot;]</value>
      <webElementGuid>c1c45f2b-c171-418a-b307-2bd6a9ee66b5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
