<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PreCanerTypes-Dd</name>
   <tag></tag>
   <elementGuidId>904a0926-d7ce-426f-9ad1-6ad691449de6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-pre-cancer-types&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-pre-cancer-types&quot;]</value>
      <webElementGuid>2d20d369-8fa5-4cce-bdf7-516b4253be4b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
