<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TargetedDataSubDeliveryDate-Txtbx</name>
   <tag></tag>
   <elementGuidId>dc49a234-f384-484f-9ae4-1811ab4d2309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-targeted-data-submission-delivery-date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-targeted-data-submission-delivery-date&quot;]</value>
      <webElementGuid>5c7171bd-3f18-4410-a628-f72fa6e40150</webElementGuid>
   </webElementProperties>
</WebElementEntity>
