<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeConstrintDescription-Txtbx</name>
   <tag></tag>
   <elementGuidId>89ab5cf4-67fe-41bf-b17b-dd38b95eed78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-time-constraint-0-description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-time-constraint-0-description&quot;]</value>
      <webElementGuid>d7eb4d80-2322-44ad-a452-16145c8bab16</webElementGuid>
   </webElementProperties>
</WebElementEntity>
