<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDS_StatBar-Participants</name>
   <tag></tag>
   <elementGuidId>c16d094f-deae-4c17-90fc-64363d746e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statsbar_count_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statsbar_count_2&quot;]</value>
      <webElementGuid>87962dbf-92ca-45b4-8d15-db4e725f05a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
