<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>C3DC_phs002504</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>902dd720-45eb-4af5-94af-c49c1b58672e</testSuiteGuid>
   <testCaseLink>
      <guid>9c953e7f-1f7a-4255-a86f-cf4dbdb450df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>157bf963-486b-482f-9a2e-afd7a2db7e55</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/C3DC_TestCases/TC04_C3DC_RowDataValidation_phs002504</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a6f51e63-2ff0-4d04-b66a-9fcf2b9b0b22</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/C3DC/phs002504</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a6f51e63-2ff0-4d04-b66a-9fcf2b9b0b22</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>157bf963-486b-482f-9a2e-afd7a2db7e55</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
