<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDC_QA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c6efefa9-fad4-4969-a83c-61dccae3795b</testSuiteGuid>
   <testCaseLink>
      <guid>4ab29519-b80c-4ef8-935f-c5cd9c37a765</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CCDC_TestCases/Participating Resources page/TC01_CCDC_Participating_Resources_page_basic_verification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11950293-a5c9-446e-a350-c001b4398dfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9283c84-5e38-4bbb-9fac-3f6a3b8cc8af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb907ceb-95a0-4220-a020-9ad7ada99092</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>278c2b61-b5ad-4c09-93f9-e4ddf7807135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d493ed3-2c61-4fe4-8f82-90cd03ae041e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8581787b-17c4-4f60-9866-4227ed754ded</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CCDC_TestCases/Search Catalog page/TC01_CCDC_Dataset_page_basic_verification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e19073c-8f9b-41fd-8e89-53000271466e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20f499a-a644-47ea-b889-5c2b1b662c0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f66100f9-9b88-4d1e-8291-0d3f78791a5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff121e25-75ff-4fdc-ab30-e6875ae4e68a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
