<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2790</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>24ed3d92-aa03-4d4e-9f82-69d78c99df82</testSuiteGuid>
   <testCaseLink>
      <guid>3f50eb7a-3bc3-4bef-9530-c399a54268a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>94f338c2-272c-430e-acb7-158173c3d9cb</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC04_CCDI_RowDataValidation_phs002790</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d50914d2-b989-458b-ac3a-64a821c1f479</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002790</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d50914d2-b989-458b-ac3a-64a821c1f479</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>94f338c2-272c-430e-acb7-158173c3d9cb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
