<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2430</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>80782142-936d-4712-883a-bffa9e572ed8</testSuiteGuid>
   <testCaseLink>
      <guid>4dd0c4fe-ebf5-4d69-9cf0-f346af589bdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>fe0964bb-3a3f-42a5-884c-d5301488c6e0</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC12_CCDI_RowDataValidation_phs002430</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f482e6f6-9ad4-4a47-83e4-e0588b5ffd32</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002430</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f482e6f6-9ad4-4a47-83e4-e0588b5ffd32</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>fe0964bb-3a3f-42a5-884c-d5301488c6e0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
