<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2599</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>56b7663e-734f-4c4e-9001-b8832654b3ec</testSuiteGuid>
   <testCaseLink>
      <guid>47be3c72-d875-4d80-a653-d0815cb04dac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>52aeb0b2-cb20-4f5b-bc95-98df5d4fe09e</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC01_CCDI_RowDataValidation_phs002599</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f6818fee-3185-465c-8720-2ae81d69e193</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002599</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f6818fee-3185-465c-8720-2ae81d69e193</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>52aeb0b2-cb20-4f5b-bc95-98df5d4fe09e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
