<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs3111</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>23457265-e5e4-4434-9e40-ba2d22115f7d</testSuiteGuid>
   <testCaseLink>
      <guid>a6eb79eb-a61c-4744-b637-1f282653d107</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>6003ea97-31c6-4098-ba83-a2fe2e364cbe</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC03_CCDI_RowDataValidation_phs003111</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>892fde09-2613-4f37-bd8f-e6cda13b15fa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs003111</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>892fde09-2613-4f37-bd8f-e6cda13b15fa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>6003ea97-31c6-4098-ba83-a2fe2e364cbe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
