<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2518</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b9f397bd-6367-484e-b2e1-94d0eac778f0</testSuiteGuid>
   <testCaseLink>
      <guid>d9b1de7b-8535-44cc-a749-f2b1c374561f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>a93c6f2b-74b1-4324-a078-d0dbff5070a7</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Canine_TestCases/CCDI_TestCases/TC02_CCDI_RowDataValidation_phs002518</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>62e5801c-2242-4b0b-b9a1-ceb8d85039d1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002518</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>62e5801c-2242-4b0b-b9a1-ceb8d85039d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>qa_participant_id</value>
         <variableId>a93c6f2b-74b1-4324-a078-d0dbff5070a7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
