<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2529</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ed096141-9864-418a-97f4-c3591affaf1f</testSuiteGuid>
   <testCaseLink>
      <guid>5246111a-d9a9-49e4-9911-87b41aa63291</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>1f551f4e-9771-4aed-ae7b-d2e1480a3f39</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC06_CCDI_RowDataValidation_phs002529</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2197738c-a732-4b7e-a2e2-dc885289bbd8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002529</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2197738c-a732-4b7e-a2e2-dc885289bbd8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>1f551f4e-9771-4aed-ae7b-d2e1480a3f39</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
