<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2790</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>24ed3d92-aa03-4d4e-9f82-69d78c99df82</testSuiteGuid>
   <testCaseLink>
      <guid>8cadadd2-0e46-4b4e-8e14-779357e3f0cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>2092253f-0ee6-4730-9e28-07e099a25b7e</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC04_CCDI_RowDataValidation_phs002790</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9d163360-0938-4ffe-891b-e06b47a95543</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002790</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9d163360-0938-4ffe-891b-e06b47a95543</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>qa_participant_id</value>
         <variableId>2092253f-0ee6-4730-9e28-07e099a25b7e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
