<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDI_DataValidation_phs2599</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>56b7663e-734f-4c4e-9001-b8832654b3ec</testSuiteGuid>
   <testCaseLink>
      <guid>d9b1de7b-8535-44cc-a749-f2b1c374561f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>e4c91430-4486-442e-b09e-79aa04944c3d</id>
         <masked>false</masked>
         <name>qa_participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CCDI_TestCases/TC01_CCDI_RowDataValidation_phs002599</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bfe6aacd-e03c-43d0-af48-0bbb22424ec4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDI/phs002599</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bfe6aacd-e03c-43d0-af48-0bbb22424ec4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>qa_participant_id</value>
         <variableId>e4c91430-4486-442e-b09e-79aa04944c3d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
