<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CDS_DataValidation-phs2790</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ab40e381-b65c-4599-b745-5fcc69273242</testSuiteGuid>
   <testCaseLink>
      <guid>4648d6cf-09c7-468a-9ae8-7778d8565826</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>8c88293a-567d-4cef-8341-fbe06cbae645</id>
         <masked>false</masked>
         <name>participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CDSDataValidation/TC02_RowDataValidation-phs002790</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>da60713b-6a6c-403b-9f36-51b7fe5ea504</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CDS/phs002790</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>da60713b-6a6c-403b-9f36-51b7fe5ea504</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>8c88293a-567d-4cef-8341-fbe06cbae645</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
