<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CDS_DataValidation-phs2432</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>075530b2-0233-4738-b674-ba6b6ad06836</testSuiteGuid>
   <testCaseLink>
      <guid>cac3b359-0392-4cc5-a9c2-366c122d2215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>c07df369-5394-4ac2-bfeb-31f5163bbb0f</id>
         <masked>false</masked>
         <name>participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CDSDataValidation/TC03_RowDataValidation-phs002432</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>21701195-aad2-457a-87c9-1eb673cbe18b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CDS/phs002432</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>21701195-aad2-457a-87c9-1eb673cbe18b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>c07df369-5394-4ac2-bfeb-31f5163bbb0f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
