<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CDS_DataTesting</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6bbb8193-6d71-44e2-958f-eac99e6e063c</testSuiteGuid>
   <testCaseLink>
      <guid>dd512da5-7675-4909-981b-4a32a50e68b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>2cd989fd-baa3-4bc9-b6a3-c058496e261e</id>
         <masked>false</masked>
         <name>participant_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/CDSDataValidation/TC01_RowDataValidation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0f2995d7-343e-458d-8b92-df9a343eb7cb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/CDS/RowDataValidation</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0f2995d7-343e-458d-8b92-df9a343eb7cb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participant_id</value>
         <variableId>2cd989fd-baa3-4bc9-b6a3-c058496e261e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
