<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ICDC_CaseDetails</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bea37010-2943-43ae-8821-e3f96fe3ca7e</testSuiteGuid>
   <testCaseLink>
      <guid>3a0cd6dc-bf5a-4614-9049-84bf8fd7e9d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Canine_TestCases/CaseDetailsPage/TC01_CaseDetails_Verification-of_basic_details</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>79cc7e52-f65b-4c31-be28-30ec0e0c7966</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ICDC_CaseDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>79cc7e52-f65b-4c31-be28-30ec0e0c7966</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseID</value>
         <variableId>42aee7ff-46e4-4f34-a2fc-b65383f0672c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79cc7e52-f65b-4c31-be28-30ec0e0c7966</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>suffixUrl</value>
         <variableId>9f84dbc6-554f-4b11-a37f-e242ad3d0d0c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
