<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Female_Chkbx</name>
   <tag></tag>
   <elementGuidId>96db1f89-ff8e-4baf-9b88-a2537bec1daf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Sex_Female&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Sex_Female&quot;]</value>
      <webElementGuid>b21cea3a-76d6-4f95-8e83-dcc5048695cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
