<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Male_Chkbx</name>
   <tag></tag>
   <elementGuidId>ecb8abb5-7ad2-41e2-80f6-bc60b8a9149a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Sex_Male&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Sex_Male&quot;]</value>
      <webElementGuid>b40c4fc4-7837-46ae-90cd-fd84be6f54d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
