<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DIAGNOSIS_Ddn</name>
   <tag></tag>
   <elementGuidId>4ae9d107-4233-4980-9cba-35cd0015fc03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@id,'Diagnosis')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@id,'Diagnosis')])[1]</value>
   </webElementProperties>
</WebElementEntity>
