<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_FilesTable_Hdr</name>
   <tag></tag>
   <elementGuidId>e761134a-f877-4f7a-850c-9548d128c09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='table_case_detail']//parent::div//parent::span//parent::th//parent::tr//parent::thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='table_case_detail']//parent::div//parent::span//parent::th//parent::tr//parent::thead</value>
   </webElementProperties>
</WebElementEntity>
