<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iConfirmDesigntdAsAor-ChkBx</name>
   <tag></tag>
   <elementGuidId>4660fa26-3d16-4c83-861b-f770ea50ece8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-ar-consent-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-ar-consent-value']</value>
      <webElementGuid>1aee177e-ea27-48cc-9b75-a3cccac5efab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
