<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NameOfAor-TxtBx</name>
   <tag></tag>
   <elementGuidId>cf58578d-5165-4112-891e-db2e4d28c159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-aor-name-0-value']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-aor-name-0-value']</value>
      <webElementGuid>f3b901cd-00f5-4ca1-b795-9b82333ebf54</webElementGuid>
   </webElementProperties>
</WebElementEntity>
