<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NCI-Match-Dd</name>
   <tag></tag>
   <elementGuidId>b8e485ec-5e0b-457c-bb1c-60ae4e8483ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-nci-match-data-access']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-nci-match-data-access']</value>
      <webElementGuid>1459d62c-1263-47ed-bceb-b37b47c4bbbf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
