<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NctNumPubMedID-TxtBx2</name>
   <tag></tag>
   <elementGuidId>48ea290e-2708-416f-bd10-7d9e852d9e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-trial-nct-number-1-target-id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-trial-nct-number-1-target-id']</value>
      <webElementGuid>74069ef2-15b3-4a53-8c46-c22d5d070334</webElementGuid>
   </webElementProperties>
</WebElementEntity>
