<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save-Btn</name>
   <tag></tag>
   <elementGuidId>42f87038-3ecc-48f6-9df2-232eef623dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-status-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-status-3']</value>
      <webElementGuid>9da1834e-fe67-4d7d-9fb3-f3ed4290d6a5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
