<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UsernameForNCI-Match-TxtBx</name>
   <tag></tag>
   <elementGuidId>35e81678-c820-41b5-be54-e49ac1a83ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-username-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-username-0-value']</value>
      <webElementGuid>d716d57f-5aa1-4022-8abe-bab71239458d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
