<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>diseaseID</name>
   <tag></tag>
   <elementGuidId>e80cc65d-d74a-4243-a152-ab2ea22f16d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;profile-page-header-block&quot;]/div[1]/div/div[2]/div[2]/p/span[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;profile-page-header-block&quot;]/div[1]/div/div[2]/div[2]/p/span[1]/a</value>
      <webElementGuid>f59566e1-c442-4ef0-83ea-f63bdd768aa4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
