<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>diseaseName</name>
   <tag></tag>
   <elementGuidId>37103553-2c90-4d18-b8ab-d37ee0053d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;profile-page-header-block&quot;]/div[1]/div/div[2]/div[1]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;profile-page-header-block&quot;]/div[1]/div/div[2]/div[1]/h4</value>
      <webElementGuid>31145301-e379-43b2-926e-c5a842d775dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
