<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCG_Chkbx</name>
   <tag></tag>
   <elementGuidId>3c4fd686-b5d8-4997-87ec-e9dceff5f54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkbox_Division/Office/Center_CCG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkbox_Division/Office/Center_CCG']</value>
      <webElementGuid>f4f96101-9838-4850-8e20-02922b68ed4b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
