<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CSSI_Chkbx</name>
   <tag></tag>
   <elementGuidId>91700c55-0f78-4a50-be34-6132af2769cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkbox_DOC_CSSI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkbox_DOC_CSSI']</value>
      <webElementGuid>f1c7faee-2249-4174-be44-2f37d5c1badc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
