<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DCB_Chkbx</name>
   <tag></tag>
   <elementGuidId>275797b2-3ce7-444b-8a94-3d98f698a7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkbox_Division/Office/Center_DCB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkbox_Division/Office/Center_DCB']</value>
      <webElementGuid>b9160fa9-0b6f-450b-b738-f65543e66a36</webElementGuid>
   </webElementProperties>
</WebElementEntity>
