<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DCCPS_Chkbx</name>
   <tag></tag>
   <elementGuidId>a4b4e1cf-8ccd-44ce-b667-5921f82a2ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkbox_DOC_DCCPS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkbox_DOC_DCCPS']</value>
      <webElementGuid>1b3b9cdf-4edd-4439-acd6-288b6004ea1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
