<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DCP_Chkbx</name>
   <tag></tag>
   <elementGuidId>9e16cb9f-8e1e-46e4-b3d1-4ff4d7941de6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkbox_Division/Office/Center_DCP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkbox_Division/Office/Center_DCP']</value>
      <webElementGuid>0db075d1-6567-46c0-92f0-a9e325b612aa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
