<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DCTD_Chkbx</name>
   <tag></tag>
   <elementGuidId>85128781-7356-413a-9684-cc07a24610a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkbox_Division/Office/Center_DCTD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkbox_Division/Office/Center_DCTD']</value>
      <webElementGuid>f878b3f4-7c02-41c8-8fc6-4deaed3b4144</webElementGuid>
   </webElementProperties>
</WebElementEntity>
