<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Controlled-Chkbx</name>
   <tag></tag>
   <elementGuidId>efee41d7-cbbb-40c2-852d-62037c9a3363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Accesses_controlled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Accesses_controlled&quot;]</value>
      <webElementGuid>57e8e79d-1fc7-4bd3-8aa1-e6fb6f7033de</webElementGuid>
   </webElementProperties>
</WebElementEntity>
