<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_Cases_Btn</name>
   <tag></tag>
   <elementGuidId>dc2964c4-0e1b-4050-9431-a3d2d63a83b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'#/explore')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'cases')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'#/explore')]</value>
   </webElementProperties>
</WebElementEntity>
