<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Designation_Input</name>
   <tag></tag>
   <elementGuidId>fc0d6f53-56d5-4b05-b85c-7a0672b08860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[2]/div/div/div/div[2]/div/div[1]/table/thead/tr[2]/th[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[2]/div/div/div/div[2]/div/div[1]/table/thead/tr[2]/th[2]/div/div/div/input</value>
      <webElementGuid>21e087dc-1757-4a35-85e0-db8a2b5fed4b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
