<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CaseDetails_SamplesTable_NxtBtn</name>
   <tag></tag>
   <elementGuidId>53d03f7c-2d20-4bc2-9659-905419f8d39e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_case_detail&quot;]/div[1]/div/div[2]/div[1]/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_case_detail&quot;]/div[1]/div/div[2]/div[1]/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>f198142d-bee2-4e0d-8cc2-ccea7a48f75f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
