<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CaseDetails_FilesTable_NxtBtn</name>
   <tag></tag>
   <elementGuidId>2067057c-76cf-40eb-8ea4-8958d997c354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_case_detail&quot;]/div[1]/div/div[2]/div[1]/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_case_detail&quot;]/div[1]/div/div[2]/div[1]/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>44ad111f-1701-469b-948a-925e19fb7b24</webElementGuid>
   </webElementProperties>
</WebElementEntity>
