<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyContainer</name>
   <tag></tag>
   <elementGuidId>46ddc01d-5760-46b0-ab04-9a0554b81468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div[2]/div/div[3]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div[2]/div/div[3]/div/div[2]</value>
      <webElementGuid>a791c242-b9d1-4ed5-a93c-9a780ad2f36a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
