<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FNLCR_HomePage_Logo</name>
   <tag></tag>
   <elementGuidId>200eefbd-8685-4c74-bd34-32dcdb19778b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;extended-mega-logo&quot;]/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;extended-mega-logo&quot;]/a/picture/img</value>
      <webElementGuid>cb3ecfbf-e535-4a57-8fbd-9749a3198333</webElementGuid>
   </webElementProperties>
</WebElementEntity>
