<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NCI_logo</name>
   <tag></tag>
   <elementGuidId>f029f94a-590a-45d3-ad10-55a981a3df14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;extended-mega-logo&quot;]/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;extended-mega-logo&quot;]/a/picture/img</value>
      <webElementGuid>39458ad1-b3a8-4dd7-8068-7fba51772186</webElementGuid>
   </webElementProperties>
</WebElementEntity>
