<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NEUTEREDSTATUS_Ddn</name>
   <tag></tag>
   <elementGuidId>fdce17bb-b990-47a1-8a63-e3f80b2f2be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Sex')]//parent::div//parent::div//parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Sex')]//parent::div//parent::div//parent::div</value>
   </webElementProperties>
</WebElementEntity>
