<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No_Chkbx</name>
   <tag></tag>
   <elementGuidId>d5ad53d4-7f0c-4a0a-b3ff-d62aa4146e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[contains(text(),'No')])[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(text(),'No')])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(text(),'No')])[5]</value>
   </webElementProperties>
</WebElementEntity>
