<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yes_Chkbx</name>
   <tag></tag>
   <elementGuidId>5588d40a-54f2-4058-8783-39d4155fd211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[contains(text(),'Yes')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(text(),'Yes')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(text(),'Yes')])[1]</value>
   </webElementProperties>
</WebElementEntity>
