<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dbGapPHSNumber-Txtbx</name>
   <tag></tag>
   <elementGuidId>c7c087c3-e778-47cf-b6cf-298dff23aec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-dbgap-phs-number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-dbgap-phs-number&quot;]</value>
      <webElementGuid>cdeb0ca4-e4fc-484b-9106-fac880c10a26</webElementGuid>
   </webElementProperties>
</WebElementEntity>
