<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundingAgency-Dd</name>
   <tag></tag>
   <elementGuidId>ff422df4-059b-4448-bcbf-432c9ffb55b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;:r8o:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;:r8o:&quot;]</value>
      <webElementGuid>4db46113-11be-4929-81f7-6f54d3dd1d37</webElementGuid>
   </webElementProperties>
</WebElementEntity>
