<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NciGPAName-Txtbx</name>
   <tag></tag>
   <elementGuidId>2234939e-ac41-4d43-8d18-86bb77a495f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;:r8t:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;:r8t:&quot;]</value>
      <webElementGuid>ebac28bd-4691-4899-9c99-8cabef9d66bf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
