<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlannedPublicationTitle-Txtbx</name>
   <tag></tag>
   <elementGuidId>6379a12c-e4b3-433f-94ab-b08b14c050bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-planned-publication-0-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-planned-publication-0-title&quot;]</value>
      <webElementGuid>776ca297-4720-43f4-8279-8cccc9dbbea8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
