<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RemovePlannedPublication-Btn</name>
   <tag></tag>
   <elementGuidId>e108d7c6-52a3-4ab0-8430-d3dfce625549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-publication-0-remove-publication-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-publication-0-remove-publication-button&quot;]</value>
      <webElementGuid>e6e0db19-f114-4cd0-b7c9-59addf6eafd5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
