<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Study-Txtbx</name>
   <tag></tag>
   <elementGuidId>f83bb264-f68b-4e91-a760-56fb7bdff8f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-study&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-study&quot;]</value>
      <webElementGuid>b158e8be-c956-4dcd-af7a-bad00ac6a0ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
