<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyName-Txtbx</name>
   <tag></tag>
   <elementGuidId>932bbd9e-b6f4-404d-852d-255aea4e98fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-study-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-study-name&quot;]</value>
      <webElementGuid>75d00bd0-71d1-4ffc-9ee0-54b3cc312856</webElementGuid>
   </webElementProperties>
</WebElementEntity>
