<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ARM_Ddn</name>
   <tag></tag>
   <elementGuidId>2d082e0e-7819-4fbd-87f1-2149752789d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='Arm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='Arm']</value>
      <webElementGuid>d634b024-68cd-4f77-9874-78f73bf54a60</webElementGuid>
   </webElementProperties>
</WebElementEntity>
