<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDS_ParticipantsTabNextBtn</name>
   <tag></tag>
   <elementGuidId>bd0ae4d6-422e-4552-bbc1-42f9bf296766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;case_tab_table&quot;]//div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;case_tab_table&quot;]//div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>b7e3248e-f1e3-48c8-94e3-7229a062527c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
