<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_StatBar-Arms</name>
   <tag></tag>
   <elementGuidId>98deae02-e4da-4187-ab4e-0afd2d9461f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statsbar_count_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statsbar_count_2&quot;]</value>
      <webElementGuid>095b9760-7cbf-4ead-a1c7-489e8d8df6b5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
