<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_StatBar-Assays</name>
   <tag></tag>
   <elementGuidId>80eafce2-b9b8-49fc-810b-990f71f60b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[1]/div[1]/div[5]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div[1]/div[1]/div[5]/div[2]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
