<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Beagle_Chkbx</name>
   <tag></tag>
   <elementGuidId>c42b637c-1661-4ce6-964a-4766a8f00966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Breed_Beagle&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Breed_Beagle&quot;]</value>
      <webElementGuid>5560faf2-5d61-4065-aa39-95caa4030d6e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
