<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boxer_Chkbx</name>
   <tag></tag>
   <elementGuidId>7965bd22-df67-4942-b17b-a8b6c68fbb04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Breed_Boxer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Breed_Boxer&quot;]</value>
      <webElementGuid>4052c16e-fd1f-43e7-874f-c4937d8dd895</webElementGuid>
   </webElementProperties>
</WebElementEntity>
