<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pomeranian_Chkbx</name>
   <tag></tag>
   <elementGuidId>3fbb6117-6cf5-42b9-aa31-b582c52d4e5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Breed_Pomeranian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Breed_Pomeranian']</value>
      <webElementGuid>66e747e0-ec77-4d54-88ce-7f2c066cc14a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
