<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//span[contains(text(),'Rottweiler')]//parent::div//parent::div</description>
   <name>Rottweiler_Chkbx</name>
   <tag></tag>
   <elementGuidId>36c1cae4-aef8-413c-8a81-41f369094e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Rottweiler')]//parent::div//parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Rottweiler')]//parent::div//parent::div</value>
   </webElementProperties>
</WebElementEntity>
