<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NctNumAndTitle-Txt</name>
   <tag></tag>
   <elementGuidId>7dba5355-8329-41f0-a527-dafa40fb5711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-trial-and-publication-wrapper']//li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-trial-and-publication-wrapper']//li</value>
      <webElementGuid>66ea6af2-6133-488e-889d-5c51cf4f068b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
