<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdditionalDataInFuture-SlidrBtn</name>
   <tag></tag>
   <elementGuidId>ae9dd3a9-0eea-4403-9a64-7e6dabe1ac19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-additional-data-in-future&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-additional-data-in-future&quot;]</value>
      <webElementGuid>26fc1f93-674e-4e3c-bc84-83f6679d4bdf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
