<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BiospecimenData-SlidrBtn</name>
   <tag></tag>
   <elementGuidId>0cd2f4f0-10f0-4bf9-a977-a76fd2125d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-biospecimen-data&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-biospecimen-data&quot;]</value>
      <webElementGuid>f926a02d-78a5-4e60-b954-25a544364bd3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
