<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DemographicData-SlidrBtn</name>
   <tag></tag>
   <elementGuidId>519a1550-0de7-4e64-a5b7-4716f5e80997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-demographic-data&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-demographic-data&quot;]</value>
      <webElementGuid>86a31f47-c8fb-432a-953b-2c6037c7819e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
