<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EstimatedAmountOfData-RowOne-Txtbx</name>
   <tag></tag>
   <elementGuidId>de388342-8d3c-4b87-87ba-9f007aa55e83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-file-type-0-amount-of-data&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-file-type-0-amount-of-data&quot;]</value>
      <webElementGuid>c1f0103d-1ee4-49cc-b232-f8470a58235f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
