<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileType-RowOne-Dd</name>
   <tag></tag>
   <elementGuidId>b03a8d2c-9633-4c06-98f7-bc5fc5db1711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-file-type-0-file-type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-file-type-0-file-type&quot;]</value>
      <webElementGuid>9bbeb299-7677-4d86-acf8-ffd9cad8d67e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
