<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileExtension-RowTwo-Dd</name>
   <tag></tag>
   <elementGuidId>301a5316-e9bc-4df3-a258-3ae68cd43d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-file-type-1-file-extension&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-file-type-1-file-extension&quot;]</value>
      <webElementGuid>2dbcb11b-d1ba-42a5-97da-e9dc0ef83584</webElementGuid>
   </webElementProperties>
</WebElementEntity>
