<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Genomics-SlidrBtn</name>
   <tag></tag>
   <elementGuidId>c092477a-a626-4add-a288-8d8f8f3b6750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-genomics&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-genomics&quot;]</value>
      <webElementGuid>8d1d2f1c-31ef-49e0-8372-cd648c7aa3da</webElementGuid>
   </webElementProperties>
</WebElementEntity>
