<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SectionD-FileTypeTable</name>
   <tag></tag>
   <elementGuidId>136b38e0-ebae-4d23-8169-6bc872df6d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[contains(@class,'MuiTable-root')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[contains(@class,'MuiTable-root')]</value>
      <webElementGuid>ccc2bba0-0e57-4c9a-aba6-01952807312f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
