<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cnvByGene_tab</name>
   <tag></tag>
   <elementGuidId>173d3f58-a3cc-4abb-9c82-0cbd1888a382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='cnvByGeneTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='cnvByGeneTab']</value>
      <webElementGuid>06f32aec-1d93-4858-9c24-e6c043859150</webElementGuid>
   </webElementProperties>
</WebElementEntity>
