<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cnvByGene_pagination</name>
   <tag></tag>
   <elementGuidId>76e2b54d-5e78-4d73-87ce-90b764c3e249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='somaticAlterationsCNVTablePagination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='somaticAlterationsCNVTablePagination']</value>
      <webElementGuid>eb301b81-07d7-40ae-bea6-d4680e8f2544</webElementGuid>
   </webElementProperties>
</WebElementEntity>
