<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DiffExpression</name>
   <tag></tag>
   <elementGuidId>8b289961-d461-4884-9541-045e6045054e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='differentialExpressionSummary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='differentialExpressionSummary']</value>
      <webElementGuid>e61224a4-1228-4150-9a68-b597ce9520a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
