<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EpiMod_methByIso_TblBdy</name>
   <tag></tag>
   <elementGuidId>438b68cd-da1c-40f9-ba58-aa91ed6da36c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;epigeneticModificationMethylationByIsoformTable&quot;]/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;epigeneticModificationMethylationByIsoformTable&quot;]/tbody</value>
      <webElementGuid>5b61e69e-91d7-4bdd-933f-a130f34ecc77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
