<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EpiMod</name>
   <tag></tag>
   <elementGuidId>a245d86a-ab08-4327-bd1d-7bbe65029b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;epigeneticModification&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;epigeneticModification&quot;]</value>
      <webElementGuid>f44ab0f7-da90-4bcf-9366-e2edf92e2e80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
