<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>epiModif_Wdgt</name>
   <tag></tag>
   <elementGuidId>2ad90915-021f-4bbb-9a26-5ad410d7c21a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='epigeneticModification_stats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='epigeneticModification_stats']</value>
      <webElementGuid>7e427f17-c04e-444e-8e74-72afd946c7b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
