<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EpiMod_methByGene_TblBdy</name>
   <tag></tag>
   <elementGuidId>ec8809e8-4e01-457f-9aed-4797cbe8ed6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;epigeneticModificationMethylationByGeneTable&quot;]/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;epigeneticModificationMethylationByGeneTable&quot;]/tbody</value>
      <webElementGuid>701370c9-5135-4b19-8cf9-c12cbb616ad0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
