<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fusion_tab</name>
   <tag></tag>
   <elementGuidId>5298068d-fe43-4829-ae3e-d79e39ffbe56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='fusionTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='fusionTab']</value>
      <webElementGuid>492f9cfa-8abf-454e-a234-c452ffbb8b2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
