<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fusionByGene_tab</name>
   <tag></tag>
   <elementGuidId>1df89721-95b3-452e-88ef-0a5c1adebc72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='fusionByGeneTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='fusionByGeneTab']</value>
      <webElementGuid>af9e45d9-6e60-48a4-8da0-408a21655508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
