<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GeneExp_Wdgt</name>
   <tag></tag>
   <elementGuidId>3525f72b-a680-4ada-ab7a-fefb16c305c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='geneExpressionSummary_stats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='geneExpressionSummary_stats']</value>
      <webElementGuid>6e8ce003-34af-4e4d-9881-1dff25794980</webElementGuid>
   </webElementProperties>
</WebElementEntity>
