<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snvByVar_tab</name>
   <tag></tag>
   <elementGuidId>44262a93-231b-410f-b7df-35c98786c28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='snvByVariantTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='snvByVariantTab']</value>
      <webElementGuid>b26f0c27-4c84-4834-ba36-43d89acef5c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
