<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SomaticAlt_TblBdy</name>
   <tag></tag>
   <elementGuidId>b0f27667-d2be-4041-96f6-bec0f77e2ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summary-section&quot;]/div[1]/div/div/div[3]/div[2]/div/div/div[2]/table//tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summary-section&quot;]/div[1]/div/div/div[3]/div[2]/div/div/div[2]/table//tbody</value>
      <webElementGuid>28575c91-72b0-4a33-8863-781d23f10e63</webElementGuid>
   </webElementProperties>
</WebElementEntity>
