<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SomAlt_snvByVar_TblBdy</name>
   <tag></tag>
   <elementGuidId>5ed73a27-2ab1-419d-b3ea-5eb5cbb69b20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;somaticAlterationsSNVByVariantTable&quot;]//tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;somaticAlterationsSNVByVariantTable&quot;]//tbody</value>
      <webElementGuid>b2aa2939-3264-4bb4-9e2f-16756f640f8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
