<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Statbar-Programs</name>
   <tag></tag>
   <elementGuidId>ff6ab931-f8e0-4e64-9c99-f0e938d78130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='statsbar_count_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='statsbar_count_1']</value>
      <webElementGuid>d0ee65bb-2928-41f6-b6ee-8fc504129c94</webElementGuid>
   </webElementProperties>
</WebElementEntity>
