<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Statbar-Patents</name>
   <tag></tag>
   <elementGuidId>e20c4367-35fd-4eb4-b44e-b56df7a8bf9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='statsbar_count_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='statsbar_count_7']</value>
      <webElementGuid>5526498f-0d2d-4558-8870-48fd251c1e40</webElementGuid>
   </webElementProperties>
</WebElementEntity>
