<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Statbar-ClinTrials</name>
   <tag></tag>
   <elementGuidId>92e21ec3-7929-43e3-b936-9dd0aba5a63a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='statsbar_count_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='statsbar_count_6']</value>
      <webElementGuid>2adce838-8f2d-4a87-bdf3-f84ed40349ca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
