<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Statbar-Publications</name>
   <tag></tag>
   <elementGuidId>fd2841d3-e01e-48a2-9ac4-6ddee9d1f192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='statsbar_count_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='statsbar_count_4']</value>
      <webElementGuid>c81c9f9a-9406-40bb-b223-0e7047926977</webElementGuid>
   </webElementProperties>
</WebElementEntity>
