<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DIAGNOSIS_Ddn</name>
   <tag></tag>
   <elementGuidId>9de74a63-e488-4311-be39-3e71b435f5f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Diagnosis')]//parent::div//parent::div//parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Diagnosis')]//parent::div//parent::div//parent::div</value>
   </webElementProperties>
</WebElementEntity>
