<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_AddAll_Yes_Btn</name>
   <tag></tag>
   <elementGuidId>53d5ad55-f5e3-4abd-a672-40dbc130cf7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[3]/div/div[2]/button[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/div[2]/button[1]/span[1]</value>
      <webElementGuid>83666e85-beed-4858-9c83-d22c62d88e8c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
