<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DIAGNOSIS_Ddn</name>
   <tag></tag>
   <elementGuidId>3fa110fa-0c78-4e5d-90fb-eda1c2eaef38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id='Diagnosis'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id='Diagnosis'])[1]</value>
   </webElementProperties>
</WebElementEntity>
