<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hemangiosarcoma_Chkbx</name>
   <tag></tag>
   <elementGuidId>e6ec9cb8-9127-4344-b40a-0e02abc9a03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Diagnosis_Hemangiosarcoma']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Diagnosis_Hemangiosarcoma']
</value>
      <webElementGuid>4f17111c-4503-40f8-b4b9-eb8131fbe27b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
