<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lymphoma_Chkbx</name>
   <tag></tag>
   <elementGuidId>f284f3bf-99f4-410d-9cd6-5af3cb20cc67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Diagnosis_Lymphoma']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='checkbox_Diagnosis_Lymphoma']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Diagnosis_Lymphoma']</value>
   </webElementProperties>
</WebElementEntity>
