<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OsteoSarcoma_Chkbx</name>
   <tag></tag>
   <elementGuidId>9dda5004-b9b3-40be-b30f-b99d21a0f50a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[contains(text(),'Osteosarcoma')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[contains(text(),'Osteosarcoma')]</value>
   </webElementProperties>
</WebElementEntity>
