<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDS_CasesTable</name>
   <tag></tag>
   <elementGuidId>2b426deb-9aa5-4e1a-b296-c85e454ca59f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;case_tab_table&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;case_tab_table&quot;]</value>
      <webElementGuid>be686647-4289-44f6-b244-10d841d88a8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
