<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDS-Study-B-Chkbx</name>
   <tag></tag>
   <elementGuidId>bec36a7c-4ee9-4927-ac78-eda2d37160bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Study_CDS-Study-B&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Study_CDS-Study-B&quot;]</value>
      <webElementGuid>92d37be4-d3cc-4278-916b-7ae721005263</webElementGuid>
   </webElementProperties>
</WebElementEntity>
