<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDS-Study-A-Chkbx</name>
   <tag></tag>
   <elementGuidId>9736fec2-7e17-42e1-8194-862362db7d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Study_CDS-Study-A&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Study_CDS-Study-A&quot;]</value>
      <webElementGuid>ddd4b25e-dbde-47ca-a991-1739715d5240</webElementGuid>
   </webElementProperties>
</WebElementEntity>
