<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nanos_gigantum_humeris_insidentes-Chkbx</name>
   <tag></tag>
   <elementGuidId>3e768032-7f90-4850-9f59-1dead3c0ead5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Study_nanos_gigantum_humeris_insidentes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Study_nanos_gigantum_humeris_insidentes&quot;]</value>
   </webElementProperties>
</WebElementEntity>
