<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Scientiae_et_patriae-Chkbx</name>
   <tag></tag>
   <elementGuidId>dfe5f490-f6f7-4121-99e8-112e63320a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Study_scientiae_et_patriae&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Study_scientiae_et_patriae&quot;]</value>
   </webElementProperties>
</WebElementEntity>
