<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_FilesTable</name>
   <tag></tag>
   <elementGuidId>6f22f801-f02d-4e73-950e-d4ca5a8f7e42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='file_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='file_tab_table']</value>
      <webElementGuid>f50bdf7c-b4de-4c1b-82cc-39c0a206a0f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
