<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_StudyFiles_Table</name>
   <tag></tag>
   <elementGuidId>25618d7e-3ac0-4987-b9ef-3a49ab00cc7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table</value>
      <webElementGuid>39688e42-a9d3-477f-810d-e7ebbb4a99fe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
