<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_StudyFilesTabNextBtn</name>
   <tag></tag>
   <elementGuidId>d37c4588-b273-40bd-9034-589abe1ca437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[1]/div[2]/div/div[2]/div[3]/div/div[4]/div/div/div[2]/div/div/div[2]/table[2]/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[1]/div[2]/div/div[2]/div[3]/div/div[4]/div/div/div[2]/div/div/div[2]/table[2]/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>3fd0e9cd-d723-4722-b354-6beb3b941ba1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
