<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_StudiesTabNextBtn</name>
   <tag></tag>
   <elementGuidId>61848186-a671-4511-a3c1-c22006a67973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;table_studies&quot;]//div[3]/button[2]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_studies&quot;]//div[3]/button[2]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_studies&quot;]//div[3]/button[2]/span[1]</value>
      <webElementGuid>8da32839-444f-4106-b832-c63b27af2fdc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
