<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_StudyFiles_TableHdr</name>
   <tag></tag>
   <elementGuidId>2ccea307-b082-4016-90d9-867bfdbfabb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table//thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//thead</value>
      <webElementGuid>81f68edb-eccf-4f4f-8a6f-86e72f098e6c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
