<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_SelectAll</name>
   <tag></tag>
   <elementGuidId>d572b6a2-ec43-4aba-b183-f3d3960ec9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;case_tab_table&quot;]//thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;case_tab_table&quot;]//thead/tr/th</value>
   </webElementProperties>
</WebElementEntity>
