<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_Files_Table</name>
   <tag></tag>
   <elementGuidId>fca9ce33-9976-4443-9fa6-602b551386d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='file_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='file_tab_table']</value>
      <webElementGuid>65eab035-50ae-47c1-9dde-77507c9c7dbc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
