<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GMB_Files_TabNextBtn</name>
   <tag></tag>
   <elementGuidId>e61d014d-80ca-40b4-be58-1e1dc90d8e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;file_tab_table&quot;]//div//div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;file_tab_table&quot;]//div//div/table/tfoot/tr/td/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
