<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_Passwd_Txtbx</name>
   <tag></tag>
   <elementGuidId>7ef5f53b-3fa0-4278-b8f9-e0005d15c727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>f82c606c-8e5b-43a1-a4eb-6db4b36c1843</webElementGuid>
   </webElementProperties>
</WebElementEntity>
