<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_PasswdNextBtn</name>
   <tag></tag>
   <elementGuidId>0739a596-7636-4893-bf52-289d8829e66b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;passwordNext&quot;]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;passwordNext&quot;]/div/button</value>
      <webElementGuid>172d60d1-a2c9-4743-a915-3c5a28d9bcb9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
