<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_ProgramsTabNextBtn</name>
   <tag></tag>
   <elementGuidId>51a1fd1c-07f9-47eb-94bb-aa395b62849a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_programs&quot;]/div/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_programs&quot;]/div/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>92738bf7-3e36-41a1-8707-7c5f669c68a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
