<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_ProgramsTable</name>
   <tag></tag>
   <elementGuidId>8502bbc1-ceff-4cce-b83e-252352ddb409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_programs&quot;]/div/div/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_programs&quot;]/div/div/div</value>
      <webElementGuid>80062108-09f5-4c78-b99e-e0b491518a69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
