<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Age_Ddn</name>
   <tag></tag>
   <elementGuidId>72172398-a81e-4d33-bb95-2edf9682dbdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@id='Age'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@id='Age'])[1]</value>
      <webElementGuid>9443cecb-e345-4052-94a6-0f42f1821951</webElementGuid>
   </webElementProperties>
</WebElementEntity>
