<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MaxAge_Input</name>
   <tag></tag>
   <elementGuidId>a0b68776-d939-4f21-9e75-947561732f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='slider_INPUT_MAX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='slider_INPUT_MAX']</value>
      <webElementGuid>5545fd8e-40d7-40a0-bafb-6d5c7143374b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
