<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>COTC007B_Hplink</name>
   <tag></tag>
   <elementGuidId>7b9b900c-50d6-481b-9183-d5203e1cc8a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href=&quot;#/study/COTC007B&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href=&quot;#/study/COTC007B&quot;]
</value>
      <webElementGuid>ee989bec-0af8-412d-bf3c-0f24aa16612f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
