<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArmDetail_NumOfCases_count</name>
   <tag></tag>
   <elementGuidId>d6b9332f-c69c-4b11-a549-aee61f6d92f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href=&quot;#/cases&quot;])[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href=&quot;#/cases&quot;])[2]/span</value>
   </webElementProperties>
</WebElementEntity>
