<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArmDetail_AssocFiles_Tbl</name>
   <tag></tag>
   <elementGuidId>ab763da2-f3c1-4486-9f04-0112841da238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='table_case_detail']//table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='table_case_detail']//table</value>
   </webElementProperties>
</WebElementEntity>
