<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tbd-Chkbx</name>
   <tag></tag>
   <elementGuidId>ea0bd2f5-524f-407f-a53b-15978dee33e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_FileType_TBD&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_FileType_TBD&quot;]</value>
      <webElementGuid>9740a8ab-a2a1-4de2-ab3a-f4b2f260919c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
