<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_totalRecordCount</name>
   <tag></tag>
   <elementGuidId>661f5528-2a8f-41dc-a687-600a42dee4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;#/fileCentricCart&quot;]//span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;#/fileCentricCart&quot;]//span/span</value>
   </webElementProperties>
</WebElementEntity>
