<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myFiles_TblHdr</name>
   <tag></tag>
   <elementGuidId>5a7f1b1c-adc1-4cb0-9d83-d3180418566a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;table_selected_files&quot;]//div//div//div/div[2]/div[3]/table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;table_selected_files&quot;]//div//div//div/div[2]/div[3]/table/thead</value>
   </webElementProperties>
</WebElementEntity>
