<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myFiles_Tbl</name>
   <tag></tag>
   <elementGuidId>c86c0e24-1a23-4828-9d5e-ef6fb55eba9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;table_selected_files&quot;]//div//div//div/div[2]/div[3]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;table_selected_files&quot;]//div//div//div/div[2]/div[3]/table</value>
   </webElementProperties>
</WebElementEntity>
