<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CDFilesTable_Bdy</name>
   <tag></tag>
   <elementGuidId>081f16e0-b56f-4168-be32-4b5a5e6fea14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='case_detail_table_associated_files']//table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='case_detail_table_associated_files']//table/tbody</value>
   </webElementProperties>
</WebElementEntity>
