<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CDFilesTable_NxtBtn</name>
   <tag></tag>
   <elementGuidId>e211a455-aa73-4efe-a13b-7e4908979951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id=&quot;table_file&quot;])[2]//table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;table_file&quot;])[2]//table/tfoot/tr/td/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
