<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CDSamplesTable_NxtBtn</name>
   <tag></tag>
   <elementGuidId>8028a7a2-5a07-4171-bb35-1fa1f6db9397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id='case_detail_table_associated_Samples']//following::button)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id='case_detail_table_associated_Samples']//following::button)[2]</value>
   </webElementProperties>
</WebElementEntity>
