<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CDSamplesTable_Hdr</name>
   <tag></tag>
   <elementGuidId>b76e66f7-098e-48fe-975c-0cfdd6b25717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='case_detail_table_associated_samples']//table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='case_detail_table_associated_samples']//table/thead</value>
   </webElementProperties>
</WebElementEntity>
