<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CDSamplesTable</name>
   <tag></tag>
   <elementGuidId>1dace9f9-3a2c-44d1-b5bf-5447d0248879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='case_detail_table_associated_samples']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='case_detail_table_associated_samples']</value>
   </webElementProperties>
</WebElementEntity>
