<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown_Chkbx</name>
   <tag></tag>
   <elementGuidId>720e1a56-1870-419f-bfc9-7551e0dab1bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//p[contains(text(),'Unknown')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//p[contains(text(),'Unknown')])[1]</value>
   </webElementProperties>
</WebElementEntity>
