<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Adenocarcinoma_Chkbx</name>
   <tag></tag>
   <elementGuidId>fdb14c7c-6286-4083-a2f7-7ceb3e5fc40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Diagnosis_Adenocarcinoma']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Diagnosis_Adenocarcinoma']</value>
   </webElementProperties>
</WebElementEntity>
