<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tumor-Chkbx</name>
   <tag></tag>
   <elementGuidId>d17c1bc7-89df-4736-a89a-168339320e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Tumor_tumor&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Tumor_tumor&quot;]</value>
      <webElementGuid>a6688200-4294-48e4-8017-f91947ed8f98</webElementGuid>
   </webElementProperties>
</WebElementEntity>
