<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cases_count</name>
   <tag></tag>
   <elementGuidId>6cdaf620-8fc9-4c87-9096-5d1cd1fec56a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href=&quot;#/cases&quot;])[2]/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href=&quot;#/cases&quot;])[2]/span[3]</value>
   </webElementProperties>
</WebElementEntity>
