<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_Filter_Study_TCL01_Chkbx</name>
   <tag></tag>
   <elementGuidId>55eaba64-705b-46fb-a947-874cf3a733a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Study_TCL01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Study_TCL01']</value>
      <webElementGuid>d544fb98-936e-4f84-a61d-897b40cf860e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
