<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DiseaseName</name>
   <tag></tag>
   <elementGuidId>ab5146c9-e567-42c0-8739-cdae7bc63d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div[2]/div[2]/div/div[1]/div/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div[2]/div[2]/div/div[1]/div/h4/a</value>
      <webElementGuid>ba252d63-a47f-42ad-b6d6-fdfa28755c55</webElementGuid>
   </webElementProperties>
</WebElementEntity>
