<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>epiMod_Wdgt</name>
   <tag></tag>
   <elementGuidId>fa3be426-1634-4592-86c7-a193c80204a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='epigeneticModificationSummary_stats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='epigeneticModificationSummary_stats']</value>
      <webElementGuid>4b9a8233-f723-49e0-b38e-b76e993db13b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
