<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Evidence_MethbyIso_Tblbdy</name>
   <tag></tag>
   <elementGuidId>31311ceb-5cde-4418-ac23-69e43b40f737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='epigeneticModificationMethylationByIsoformTable']/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='epigeneticModificationMethylationByIsoformTable']/tbody</value>
      <webElementGuid>78b02aad-fccb-462f-85a5-1ae8b5b383c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
