<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fusion_pagination</name>
   <tag></tag>
   <elementGuidId>f63d4953-99de-43a4-8c2b-4843cdf1c5dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='somaticAlterationsfusionTablePagination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='somaticAlterationsfusionTablePagination']</value>
      <webElementGuid>6dd5dd20-cbcb-4c2d-93a8-71d03c83db47</webElementGuid>
   </webElementProperties>
</WebElementEntity>
