<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fusionByGene_Cnt</name>
   <tag></tag>
   <elementGuidId>c7a12c82-0070-4752-9f62-ed6a3ddd6e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='somaticAlterationsFusionByGeneTablePagination']/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='somaticAlterationsFusionByGeneTablePagination']/div/p[2]</value>
      <webElementGuid>00a5fd6f-2645-4264-9ae2-9301dc582dbf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
