<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GeneExp</name>
   <tag></tag>
   <elementGuidId>b9f88403-b40b-4f92-9f0d-62f3ac3a4c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='geneExpressionSummary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='geneExpressionSummary']</value>
      <webElementGuid>b6f046a8-4ef5-4cd0-b705-224fdb2b6f33</webElementGuid>
   </webElementProperties>
</WebElementEntity>
