<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GeneExp_Wdgt</name>
   <tag></tag>
   <elementGuidId>4f0524b2-3d2b-480f-ba4a-a115cb164525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='geneExpressionSummary_stats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='geneExpressionSummary_stats']</value>
      <webElementGuid>65a72717-57cb-4ba8-9214-e67051bad2c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
