<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>methByGene_Cnt</name>
   <tag></tag>
   <elementGuidId>6227cdab-7689-4b89-9bfc-c9c9ccd0b378</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='epigeneticModificationMethylationByGeneTablePagination']/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='epigeneticModificationMethylationByGeneTablePagination']/div/p[2]</value>
      <webElementGuid>8d805160-9cf5-43ef-9ee5-cf79266b1d6f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
