<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>methByGene_Tab</name>
   <tag></tag>
   <elementGuidId>fce712c4-cc27-43b0-a76d-f82eee6977fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='methylationByGeneTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='methylationByGeneTab']</value>
      <webElementGuid>f37463ff-2d08-4259-aeb0-76b3a884111e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
