<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snvByVar_tab</name>
   <tag></tag>
   <elementGuidId>9c55d969-f605-4359-8c7e-cc793cef72c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='snvByVariantTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='snvByVariantTab']</value>
      <webElementGuid>416f82df-ed13-4213-855c-8252aa131312</webElementGuid>
   </webElementProperties>
</WebElementEntity>
