<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snvByGene_pagination</name>
   <tag></tag>
   <elementGuidId>ca20e8df-f664-43c1-9de5-a67a8aa07af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='somaticAlterationsSNVByGeneTablePagination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='somaticAlterationsSNVByGeneTablePagination']</value>
      <webElementGuid>a254f073-4b2c-4cd2-a029-4d2decd23f2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
