<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SomAlt_cnvByGene_TblBdy</name>
   <tag></tag>
   <elementGuidId>07281158-a993-45fa-a44f-818ed692d16a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;somaticAlterationsCNVTable&quot;]//tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;somaticAlterationsCNVTable&quot;]//tbody</value>
      <webElementGuid>1bb799c2-511a-469f-8c57-e384aa56d87e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
