<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SomaticAlt_Wdgt</name>
   <tag></tag>
   <elementGuidId>07949d8e-224e-49cb-96d0-117e3cfec813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='somaticAlterationsSummary_stats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='somaticAlterationsSummary_stats']</value>
      <webElementGuid>72169bb2-3a62-441f-8018-e7097f8e74e7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
