<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boxer_Chkbx</name>
   <tag></tag>
   <elementGuidId>f5ca9645-d3cc-4320-bf0f-4c1713f7cf24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Boxer')]//parent::div//parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Boxer')]//parent::div//parent::div</value>
   </webElementProperties>
</WebElementEntity>
