<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BREED_Ddn</name>
   <tag></tag>
   <elementGuidId>6f257b02-c9b7-435d-b48b-50e402089d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Breed')]//parent::div//parent::div//parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Breed')]//parent::div//parent::div//parent::div</value>
   </webElementProperties>
</WebElementEntity>
