<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Greyhnd_Chkbx</name>
   <tag></tag>
   <elementGuidId>0ada1c13-6ba5-4c2e-919e-eb26d127b11a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Greyhound')]//parent::div//parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Greyhound')]//parent::div//parent::div</value>
   </webElementProperties>
</WebElementEntity>
