<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Osteosarcoma_Chkbx</name>
   <tag></tag>
   <elementGuidId>1ca1b42b-7945-41fa-ac8b-2deb05299680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//p[contains(text(),'Osteosarcoma')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//p[contains(text(),'Osteosarcoma')])[2]</value>
   </webElementProperties>
</WebElementEntity>
