<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Subjects</name>
   <tag></tag>
   <elementGuidId>7d45de2b-6607-46fa-800c-9923bcc280f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='button_navbar_navButton']/span/a)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d236b59-7957-449e-b8a0-7f79acb934dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss18 jss38</value>
      <webElementGuid>e96a7f7c-3667-4589-aa7b-4de5976971e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/subjects</value>
      <webElementGuid>233073b2-0f0d-40b6-8946-a540dba58228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subjects</value>
      <webElementGuid>dbd22f8b-4feb-4a8a-9256-a8ea6b378b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/button[@id=&quot;button_navbar_navButton&quot;]/span[@class=&quot;MuiButton-label&quot;]/a[@class=&quot;jss18 jss38&quot;]</value>
      <webElementGuid>9e2e6da0-4997-4ea9-a2cf-163a317dae92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='button_navbar_navButton']/span/a)[4]</value>
      <webElementGuid>1c311643-da0e-46d2-bea0-ea1e4e1be4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Subjects')]</value>
      <webElementGuid>a9ad8365-f79d-45e7-abc7-f2ca01deba16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sites'])[1]/following::a[1]</value>
      <webElementGuid>55e50546-2e0e-49c9-8c06-d96234ed473c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='trials'])[1]/following::a[2]</value>
      <webElementGuid>e501697a-0cf5-4e83-b8b1-082f95d4ccfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='about'])[1]/preceding::a[1]</value>
      <webElementGuid>1e991904-31a0-47f6-a1d7-6be02d9fec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bento'])[1]/preceding::a[1]</value>
      <webElementGuid>0f4427f3-2967-4619-9af4-d459a8818927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subjects']/parent::*</value>
      <webElementGuid>803ed688-9bae-4c98-a0e0-a6d59069ffd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/subjects')]</value>
      <webElementGuid>051c42ee-676e-40c4-aa8d-625b04b699bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span/a</value>
      <webElementGuid>2c78d8ca-7109-43e3-a2a4-d67b09ae9ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/subjects' and (text() = 'Subjects' or . = 'Subjects')]</value>
      <webElementGuid>0992e435-334a-449d-a528-67167b3e74d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
