<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Race</name>
   <tag></tag>
   <elementGuidId>a2041568-f477-4d59-9ca5-7b5e9b6e21dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiExpansionPanelSummary-content.jss245 > #Race</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='Race'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34e19f0d-81e1-4f9d-b8f2-7eeeb0bf9b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Race</value>
      <webElementGuid>e685d429-1af2-43c1-ae1b-d0b0135fb593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss187</value>
      <webElementGuid>6f1879b5-f4b2-4f94-b71b-2021d67b1ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Race</value>
      <webElementGuid>ebf4f0c6-595e-417f-921c-115401bfa643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss2&quot;]/div[@class=&quot;jss122&quot;]/div[2]/div[@class=&quot;jss126&quot;]/div[@class=&quot;jss140&quot;]/div[1]/div[1]/div[1]/nav[@class=&quot;MuiList-root jss167 MuiList-padding&quot;]/div[@class=&quot;MuiPaper-root MuiExpansionPanel-root jss178 Mui-expanded MuiExpansionPanel-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@id=&quot;Filter By Subject&quot;]/div[@class=&quot;MuiExpansionPanelDetails-root jss181&quot;]/div[@class=&quot;MuiList-root MuiList-dense&quot;]/div[@class=&quot;MuiPaper-root MuiExpansionPanel-root jss179 MuiPaper-elevation1&quot;]/div[@id=&quot;Race&quot;]/div[@class=&quot;MuiExpansionPanelSummary-content jss245&quot;]/div[@id=&quot;Race&quot;]</value>
      <webElementGuid>e51086dc-49b4-479e-b235-4ee080a727d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='Race'])[2]</value>
      <webElementGuid>9dfb1c8f-b9b7-40d4-90e8-15fe82fec42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Race']/div/div</value>
      <webElementGuid>c27f6d8b-4cb4-4df7-b284-a426c8a75733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCT04706663'])[1]/following::div[8]</value>
      <webElementGuid>aaa9ff13-b3c5-41f0-9eab-2f7ef47d3aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort alphabetically'])[2]/preceding::div[2]</value>
      <webElementGuid>e7b1573b-5657-411e-a6a3-71cbc59e1f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by counts'])[2]/preceding::div[2]</value>
      <webElementGuid>f755e7d4-1a32-4a24-bbed-646521f12e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Race']/parent::*</value>
      <webElementGuid>b6b2a725-6558-489b-9277-6947fa4979e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/div</value>
      <webElementGuid>69d02d19-9b4e-4b91-81e3-6b5e08ff86d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Race' and (text() = 'Race' or . = 'Race')]</value>
      <webElementGuid>307d79bd-eff3-42cf-a26d-3cc8aeac6dac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
