<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(3)_checkbox_Race_Other</name>
   <tag></tag>
   <elementGuidId>1d860512-01f4-4f73-bd6a-e5a8ab76e4a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox_Race_Other</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox_Race_Other']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeda4751-bc21-4c26-9b0b-908911ac674a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss266</value>
      <webElementGuid>46a08cf9-8cd2-4664-8dca-0a1c3938f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox_Race_Other</value>
      <webElementGuid>09c04c50-6e3d-4c91-9023-79c9fefbc84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1ae5b525-d564-4b97-bc5d-ce457b3bff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f2db9f15-547b-4e24-8884-5fbe385d94c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4b20de8-b1ea-43cd-becf-b4747dc45fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_Race_Other&quot;)</value>
      <webElementGuid>202a9da3-cf9e-4b0d-995c-9b65def8ab2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox_Race_Other']</value>
      <webElementGuid>c15fa32f-42a8-485b-aaa4-356b75bb014a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Race']/div/div/div[3]/span/span/input</value>
      <webElementGuid>6aeb48d8-b026-4e60-acf4-b48ccdcddae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/input</value>
      <webElementGuid>76656304-5d53-4d99-873f-b3de638c4311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox_Race_Other' and @type = 'checkbox']</value>
      <webElementGuid>4599c4ca-7eb8-4f92-88e4-55cf3548fc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
