<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AorEmail-TxtBx</name>
   <tag></tag>
   <elementGuidId>7a7e6d9d-b416-4c1a-ad47-01a66852ee22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-aor-email-0-value']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-aor-email-0-value']</value>
      <webElementGuid>5b17aad8-590c-4e7b-899e-fc8df5cc3400</webElementGuid>
   </webElementProperties>
</WebElementEntity>
