<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AorTitle-TxtBx</name>
   <tag></tag>
   <elementGuidId>8791d9fe-d327-49ce-8475-ee4aae8164e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-aor-title-0-value']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-aor-title-0-value']</value>
      <webElementGuid>c91fe056-d61f-4066-8bb8-00e28b36af3b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
