<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IwilBeTheOnlyPerson-RidioBtn</name>
   <tag></tag>
   <elementGuidId>2b4c3ee6-a09e-4024-8fe8-d1a1ae7b3812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-other-0']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-other-0']</value>
      <webElementGuid>b63b845c-97fb-4df4-8968-2feee245f868</webElementGuid>
   </webElementProperties>
</WebElementEntity>
