<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NctNumberPubMedID-TxtBx3</name>
   <tag></tag>
   <elementGuidId>cf78ee6e-2a5a-48b4-8294-0e492240bfb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-trial-nct-number-2-target-id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-trial-nct-number-2-target-id']</value>
      <webElementGuid>dbed6979-6088-47ad-a7a8-5a79cbb31b40</webElementGuid>
   </webElementProperties>
</WebElementEntity>
