<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThereWilBeOtherPerson-RidioBtn</name>
   <tag></tag>
   <elementGuidId>eb20aeed-84a3-45fc-abb2-0995102a7eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-request-other-1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-request-other-1']</value>
      <webElementGuid>b5b17ecb-464d-4f6e-a352-84ab25e87547</webElementGuid>
   </webElementProperties>
</WebElementEntity>
