<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Back-Btn</name>
   <tag></tag>
   <elementGuidId>bf16b85e-f0e4-46cd-9da5-9ca28c1a4a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;submission-form-back-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;submission-form-back-button&quot;]</value>
      <webElementGuid>73fdd6b8-596d-42b3-a96b-add5727f65b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
