<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save-Btn</name>
   <tag></tag>
   <elementGuidId>9625736c-2b77-4df9-a930-c7bfed173be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;submission-form-save-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;submission-form-save-button&quot;]</value>
      <webElementGuid>5b2ae74d-ea4c-4111-9d5b-579a7e855451</webElementGuid>
   </webElementProperties>
</WebElementEntity>
