<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BlkAfrAmer_Chkbx</name>
   <tag></tag>
   <elementGuidId>eb6c8401-e10e-4a23-913e-dce64f8230f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id,'checkbox_Race_BLACK_OR_AFRICAN_AMERICAN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@id,'checkbox_Race_BLACK_OR_AFRICAN_AMERICAN')]</value>
   </webElementProperties>
</WebElementEntity>
