<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Moonshot_Chkbx</name>
   <tag></tag>
   <elementGuidId>796bee8f-409c-49e7-b1d8-829631383275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Program_Moonshot']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Program_Moonshot']</value>
      <webElementGuid>bb75218c-3133-46ec-9591-cf26b9c71c34</webElementGuid>
   </webElementProperties>
</WebElementEntity>
