<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Program_Ddn</name>
   <tag></tag>
   <elementGuidId>8caec5c8-acdd-45b8-9c02-de023bfb73f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id='Program'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id='Program'])[1]</value>
      <webElementGuid>5abdfa4f-dcd6-442f-8865-84e7a8bafbfd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
