<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bladder_Chkbx</name>
   <tag></tag>
   <elementGuidId>ac109790-c634-405e-a6b7-024f89462350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(text(),'Bladder')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(text(),'Bladder')])[2]</value>
   </webElementProperties>
</WebElementEntity>
