<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Brain_Chkbx</name>
   <tag></tag>
   <elementGuidId>e90e447f-032f-4bf9-9d51-30dffc473a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Brain')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),'Brain')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),'Brain')]</value>
   </webElementProperties>
</WebElementEntity>
