<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lung_Chkbx</name>
   <tag></tag>
   <elementGuidId>d24b21c3-b64c-487a-a778-8a73daaf0c58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Lung')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),'Lung')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),'Lung')]</value>
   </webElementProperties>
</WebElementEntity>
