<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mouth_Chkbx</name>
   <tag></tag>
   <elementGuidId>1d3024ed-91ad-410d-bcdb-36c57915b9c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Lung')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),'Mouth')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),'Mouth')]</value>
   </webElementProperties>
</WebElementEntity>
