<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArmsCohortsTab_Tbl</name>
   <tag></tag>
   <elementGuidId>a092d51f-3563-4fde-b381-06018f9eedc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_cohort_dosing&quot;]/p/div/div[3]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_cohort_dosing&quot;]/p/div/div[3]/table</value>
      <webElementGuid>b464ef83-5572-442d-93d8-4f0895e5876a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
