<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArmsCohortsTab_TblHdr</name>
   <tag></tag>
   <elementGuidId>8863f563-a153-408b-b1f8-6569e3a102b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role=&amp;quot;tabpanel&amp;quot;][2]/div/div/div/div[2]/table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@role=&amp;quot;tabpanel&amp;quot;][2]/div/div/div/div[2]/table/thead</value>
      <webElementGuid>11b7f345-b696-4545-843e-2543de08eaba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
