<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArmsCohortsTab_NextBtn</name>
   <tag></tag>
   <elementGuidId>ea916826-1496-45ad-81a5-6abc3190d48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_cohort_dosing&quot;]/p/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_cohort_dosing&quot;]/p/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>c97eedd1-65e5-4009-9f73-2a0446281595</webElementGuid>
   </webElementProperties>
</WebElementEntity>
