<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyFilesTab_Tbl</name>
   <tag></tag>
   <elementGuidId>930ef7c4-d61f-4c0e-8185-3e08188b3110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_associated_files&quot;]/div/div[1]/div/div/div[3]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_associated_files&quot;]/div/div[1]/div/div/div[3]/table</value>
      <webElementGuid>5e821f30-116b-4ab7-abcc-edccbad9fb15</webElementGuid>
   </webElementProperties>
</WebElementEntity>
