<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyFilesTab_NextBtn</name>
   <tag></tag>
   <elementGuidId>7af3d53c-074e-415a-95d0-5de693e87339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_associated_files&quot;]/div/div[1]/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_associated_files&quot;]/div/div[1]/div/div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      <webElementGuid>d3817bb4-f5d1-41df-9fc5-8168518fedfb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
