<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PgmDesc</name>
   <tag></tag>
   <elementGuidId>dd1607b2-57d2-4bfe-813f-83cc1c7b60fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@data-testid='content'])[${indexD}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@data-testid='content'])[${indexD}]</value>
      <webElementGuid>ecf80a4b-2877-4ffc-8043-9ec586b1230a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
