<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PgmHeader</name>
   <tag></tag>
   <elementGuidId>35ee720b-b474-4eba-a543-6c227ee9746b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-testid='header'])[${indexH}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-testid='header'])[${indexH}]</value>
      <webElementGuid>592acab0-63b9-48ac-a2ad-67b41c6d447b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
