<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyCnt</name>
   <tag></tag>
   <elementGuidId>8eb38bd1-9678-44f3-9062-b6f03c1f0c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div[2]/div/div[${indexC}]/div/div/div[2]/div[2]/span[1]/button/span[1]/a/span[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div[2]/div/div[${indexC}]/div/div/div[2]/div[2]/span[1]/button/span[1]/a/span[2]/span/span</value>
      <webElementGuid>6cc39911-9b7f-4571-bb25-61d438ade205</webElementGuid>
   </webElementProperties>
</WebElementEntity>
