<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DtstSummaryCnt</name>
   <tag></tag>
   <elementGuidId>10054778-a7ab-4bb3-80f9-b004e542399d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='dataset_summaries_detail_count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='dataset_summaries_detail_count']</value>
      <webElementGuid>eb96623f-f447-4909-b768-b396f21e5228</webElementGuid>
   </webElementProperties>
</WebElementEntity>
