<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_LocalSearch_Upld-View_CaseSet_Btn</name>
   <tag></tag>
   <elementGuidId>69a8c946-521e-4408-984a-f38ed6a40aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='localFindUploadCaseSetButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='localFindUploadCaseSetButton']</value>
   </webElementProperties>
</WebElementEntity>
