<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_LocalSearch_Upld_Submit_Btn</name>
   <tag></tag>
   <elementGuidId>7f9b1e81-3139-4a60-b9bc-847254821c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@id='uploadCaseSetSubmit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@id='uploadCaseSetSubmit'])[3]</value>
   </webElementProperties>
</WebElementEntity>
