<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_LocalSearch_Upld_MismatchCount</name>
   <tag></tag>
   <elementGuidId>63e41e99-fb3e-4317-a846-11fb53e73f2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='uploadCaseSetUnMatchedCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='uploadCaseSetUnMatchedCount']</value>
   </webElementProperties>
</WebElementEntity>
