<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_LocalSearch_UpldCaseSet_Btn</name>
   <tag></tag>
   <elementGuidId>c2b6abcb-feee-4958-bcbe-79d595e62ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;localFindUploadCaseSetButton&quot;]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;localFindUploadCaseSetButton&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
