<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_GoToCart_Hplink</name>
   <tag></tag>
   <elementGuidId>0e9b503d-164d-422c-81ed-faae173fef9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@href=&quot;#/fileCentricCart&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@href=&quot;#/fileCentricCart&quot;])[2]</value>
   </webElementProperties>
</WebElementEntity>
