<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_LocalSearch_Upld_Cancel_Btn</name>
   <tag></tag>
   <elementGuidId>c9aa0318-e5a7-4680-8c39-cd3889714392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@id='uploadCaseSetCancel'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@id='uploadCaseSetCancel'])[3]</value>
   </webElementProperties>
</WebElementEntity>
