<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_LocalSearch_Upld_TxtArea</name>
   <tag></tag>
   <elementGuidId>afffe1e8-90e0-41c9-9506-f937e85700d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//textarea[@name='caseDescription'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//textarea[@name='caseDescription'])[3]</value>
   </webElementProperties>
</WebElementEntity>
