<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExploreTheSite_Btn</name>
   <tag></tag>
   <elementGuidId>63037e61-79a5-4a94-ae3c-c00dbc7cf2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@href=&quot;#/cases&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@href=&quot;#/cases&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
