<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DiseaseCount</name>
   <tag></tag>
   <elementGuidId>b61a43f1-e8d4-4c70-8d3b-11966edcac25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div[3]/div[1]/h6/strong[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div[3]/div[1]/h6/strong[1]/span</value>
      <webElementGuid>74060797-68f2-4e09-b1d7-38f2480e9cd9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
