<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TargetID</name>
   <tag></tag>
   <elementGuidId>f75d921b-7f09-4324-985c-15dd28ba521f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;profile-page-header-block&quot;]/div[1]/div/div[2]/div[2]/p/span[1]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;profile-page-header-block&quot;]/div[1]/div/div[2]/div[2]/p/span[1]/a</value>
      <webElementGuid>dd3af0d2-3382-40e1-b9b9-2d06988e722f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
