<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NIH_Hplink</name>
   <tag></tag>
   <elementGuidId>047eda93-d950-45d0-9003-a3f9f9b60d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;https://www.nih.gov&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;https://www.nih.gov&quot;]</value>
   </webElementProperties>
</WebElementEntity>
