<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Disease_Input</name>
   <tag></tag>
   <elementGuidId>5a31b4ef-9496-431d-844a-a9ac1ffa0503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;react-select-3-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;react-select-3-input&quot;]</value>
      <webElementGuid>9091e01d-12c1-4574-9852-4fc08ab37e6d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
