<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GeneSymb_Input</name>
   <tag></tag>
   <elementGuidId>daaebef6-fd10-4061-ab7b-a34403349a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;react-select-2-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;react-select-2-input&quot;]</value>
      <webElementGuid>ecffd081-72ad-4246-8f87-683f2d2c6b08</webElementGuid>
   </webElementProperties>
</WebElementEntity>
