<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResultsCount</name>
   <tag></tag>
   <elementGuidId>3f34705c-183f-423a-9ed5-91e2c6d5a125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div[2]/div[1]/div/p/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div[2]/div[1]/div/p/strong</value>
      <webElementGuid>a819b8a5-8267-44f8-8493-caa540f1103e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
