<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_ClinTrials_Tbl</name>
   <tag></tag>
   <elementGuidId>2aa599c0-f0c7-47b8-bd58-f84627acca53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;clinical_trial_tab_table&quot;]/div/div[2]/div[3]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;clinical_trial_tab_table&quot;]/div/div[2]/div[3]/table</value>
      <webElementGuid>b883760f-af3d-4b30-abee-7e756ba5f4a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
