<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Projects_Tbl</name>
   <tag></tag>
   <elementGuidId>b0753682-d355-4d29-8910-360b9bdc80e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;project_tab_table&quot;]/div/div[2]/div[2]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;project_tab_table&quot;]/div/div[2]/div[2]/table</value>
      <webElementGuid>b802a7fd-2131-48f6-871e-01012c33755c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
