<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Publications_TblHdr</name>
   <tag></tag>
   <elementGuidId>8a4ecc62-a7d3-4f31-878a-d309d6028bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;publication_tab_table&quot;]/div/div[2]/div[3]/table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;publication_tab_table&quot;]/div/div[2]/div[3]/table/thead</value>
      <webElementGuid>3b42091e-7d2b-45ce-9493-be7a0d3981b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
