<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS_Grants_TblHdr</name>
   <tag></tag>
   <elementGuidId>d8a2a6db-851c-43a8-83a5-cf95d88d7fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;project_tab_table&quot;]/div/div[2]/div[3]/table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;project_tab_table&quot;]/div/div[2]/div[3]/table/thead</value>
      <webElementGuid>c2f8b53e-b535-41ba-9d0d-ca202bac310b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
