<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>About_Dd</name>
   <tag></tag>
   <elementGuidId>fca7fd38-c325-4581-b6b3-02e891a0cf0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-dropdown-about&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-dropdown-about&quot;]</value>
      <webElementGuid>58e174d7-15b2-43d9-8b2d-85bcf1139369</webElementGuid>
   </webElementProperties>
</WebElementEntity>
