<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CrdcSubmisnRequests-Link</name>
   <tag></tag>
   <elementGuidId>2a120d53-a216-4f5c-9932-e8f63f39a273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-dropdown-item-crdc-submission-requests&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-dropdown-item-crdc-submission-requests&quot;]</value>
      <webElementGuid>3ab17e62-7633-46bd-8344-e32108e20b50</webElementGuid>
   </webElementProperties>
</WebElementEntity>
