<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JoinCrdcDataHub-Dd</name>
   <tag></tag>
   <elementGuidId>6a044cc0-d9cc-49f4-b492-a02fb543e3a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-dropdown-join-crdc-data-hub&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-dropdown-join-crdc-data-hub&quot;]</value>
      <webElementGuid>93f8d0c0-493e-4c6a-8272-90aa909bf17d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
