<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RemoveLaterApplicationApproved</name>
   <tag></tag>
   <elementGuidId>f6e2c020-853d-4a17-96d4-ca1288cb8ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div/ul/li[1]/a</value>
      <webElementGuid>bfc8dd84-284c-4a8b-afb0-415b6862612e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
