<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Start_a_SubmissionRequest-Btn</name>
   <tag></tag>
   <elementGuidId>2a120d53-a216-4f5c-9932-e8f63f39a273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;:r2:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;:r2:&quot;]</value>
      <webElementGuid>7dea0fa5-65df-4ece-a0d3-f023814de180</webElementGuid>
   </webElementProperties>
</WebElementEntity>
