<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-Btn</name>
   <tag></tag>
   <elementGuidId>45b2e76a-be78-4bc3-9b00-f6be9ba10439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='edit-submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='edit-submit']</value>
      <webElementGuid>a7e583d0-8136-4f14-958a-ee46368f9afa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
