<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password-TxtBx</name>
   <tag></tag>
   <elementGuidId>e8d3ae04-e4f8-4604-88e4-d19cbfa16888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='edit-pass']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='edit-pass']</value>
      <webElementGuid>a5a38fce-e67a-439f-924d-5a301550a8b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
