<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserName-TxtBx</name>
   <tag></tag>
   <elementGuidId>238bb692-d3c5-4202-8c82-fe3ba2d1d1d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='edit-name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='edit-name']</value>
      <webElementGuid>265e5e5b-31bf-452e-ac0a-2d507ebb954a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
