<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Documentation_Hplink</name>
   <tag></tag>
   <elementGuidId>e3855e0a-ffcb-4615-a96d-1aba2daed185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;https://cbiit.github.io/bento-docs/&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;https://cbiit.github.io/bento-docs/&quot;]</value>
   </webElementProperties>
</WebElementEntity>
