<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FNLCR_Logo</name>
   <tag></tag>
   <elementGuidId>c3f2edb9-0573-447b-83f2-739b867b4c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div/div[1]/div[1]/a/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div/div[1]/div[1]/a/div[1]</value>
      <webElementGuid>ae0d87f6-7ebb-4d4e-9c4b-afe382a5fda1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
