<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CDFilesTable_Hdr</name>
   <tag></tag>
   <elementGuidId>46e91bcc-b4dc-4255-9f78-db9d45fdebf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id=&quot;table_file&quot;])[2]//table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;table_file&quot;])[2]//table/thead</value>
   </webElementProperties>
</WebElementEntity>
