<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_SelectAll</name>
   <tag></tag>
   <elementGuidId>3930559e-a546-460f-a0f7-20824b579267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//thead//span/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead//span/span/input</value>
   </webElementProperties>
</WebElementEntity>
