<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CasesTableHeader</name>
   <tag></tag>
   <elementGuidId>0f8c7cba-ebd6-4dab-89f5-7824d3916a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;case_tab_table&quot;]//thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;case_tab_table&quot;]//thead</value>
   </webElementProperties>
</WebElementEntity>
