<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_CasesTabNextBtn</name>
   <tag></tag>
   <elementGuidId>4cc186c3-9d0e-4fab-bbb3-4497e0489f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_cases&quot;]//div/table/tfoot/tr/td/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_cases&quot;]//div/table/tfoot/tr/td/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
