<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NctNumAndTitle-Txt</name>
   <tag></tag>
   <elementGuidId>c90de1bd-c830-4766-8989-20a6fb504601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-field-trial-and-publication-wrapper']//li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-field-trial-and-publication-wrapper']//li</value>
      <webElementGuid>472d5520-20d5-4719-b27b-b80d1d93da8a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
