<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next-Btn</name>
   <tag></tag>
   <elementGuidId>987c54fd-0bc6-4742-bd19-3a7e698caae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='edit-next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='edit-next']</value>
      <webElementGuid>9c354436-6312-4f9f-a5a4-04f3e7efb85d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
